config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated do
      root to: 'groups#index'
    end

    unauthenticated do
      root to: 'splash#index', as: 'unauthenticated_root'
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :splash, only: [:index]
  resources :entities, only: %i[new create destroy] do
    resources :relations, only: [:create]
  end
  resources :groups, only: %i[index show new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :relations, dependent: :destroy
  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def created_at
    attributes['created_at'].strftime('%d %b %Y')
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :relations, dependent: :destroy
  validates :name, presence: true
  validates :icon, presence: true

  def created_at
    attributes['created_at'].strftime('%d %b %Y')
  end

  def self_total(id)
    group = Group.find(id)
    relations = group.relations
    @total = 0
    relations.each do |relation|
      entity = Entity.find(relation.entity_id)
      @total += entity.amount
    end
    @total
  end
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :entities, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ActionController::Base
  def new
    @entity = current_user.entities.new
    @relation = Relation.new(entity: @entity)
  end

  def create
    entity = current_user.entities.new(entity_params)
    respond_to do |format|
      format.html do
        if entity.save
          relation = Relation.create(group_id: group_params, entity_id: entity.id)
          redirect_to group_path(relation.group_id)
        else
          render :new
        end
      end
    end
  end

  def destroy
    @entity = current_user.entities.find(params[:id])
    @entity.destroy
    redirect_to groups_path
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end

  def group_params
    params[:entity][:relation][:group_id]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ActionController::Base
  def index
    @groups = current_user.groups.all
  end

  def show
    @group = Group.find(params[:id])
    @relations = @group.relations.order('created_at DESC')
  end

  def new
    @group = current_user.groups.new
  end

  def create
    group = current_user.groups.new(group_params)
    respond_to do |format|
      format.html do
        if group.save
          redirect_to groups_path
        else
          render :new
        end
      end
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/relations_controller.rb
class RelationsController < ActionController::Base
  def new
    @group = Group.all
    @entity = current_user.entities.new
    @relation = Relation.new
  end
end

app/controllers/splash_controller.rb
class SplashController < ActionController::Base
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <section class="body">
      <div class="box form">
        <h1>Add New Transaction</h1>

        <%= form_with model: @entity do |f| %>

          <div class="mb-3">
            <%= f.label :name %>
            <%= f.text_field :name, required: true, class: "form-control"%>
          </div>

          <div class="mb-3">
              <%= f.label :amount %>
              <%= f.number_field :amount, required: true, min: 1, class: "form-control"%>
          </div>
        
          <div class="mb-3">
            <%= f.fields_for(@relation) do |r| %>
              <%= r.label :group%>
              <%= r.select :group_id, current_user.groups.collect { |group| [group.name, group.id]}, {include_blank: true}, required: true, class: "form-control"%>
            <% end %>   
          </div>

          <div class="mb-3">
            <%= f.submit class: "first-btn" %>
          </div>

        <%end%>
      </div>
    </section>


  </body>
</html>

app/views/groups/index.html.erb
<%= render "partials/navbar" %>

<section class="main">


    <%@groups.each do |group|%>
    
      <div class="category">
        <img src=<%=group.icon%> alt="icon">

        <div class="flex">
        <%= link_to group_path(group.id), :remote => true do %>
          <h3><%=group.name%></h3>
        <%end%>
        <p><%=group.created_at%></p>
        </div>
        <div class="flex">
        <h3><%=group.self_total(group.id)%></h3>
        <%= button_to "Delete", group_path(group.id), html: {'data-turbo' => "false"}, :method => :delete, class: "btn btn-danger" %>
        </div>

      </div>
    <%end%>
    
<%= link_to new_group_path, :remote => true do %>
  <input type="button" class="btn btn-primary last" value="Add Category">
<% end %>

</section>

app/views/groups/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <section class="body">
    <div class="box">

    <h1>Add A New Category</h1>

<%= form_with model: @group do |f| %>
      
  <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: "form-control"%>
  </div>

  <div class="mb-3">
      <%= f.label :icon %>
      <%= f.text_field :icon, required: true, class: "form-control"%>
  </div>

  <div class="mb-3">
      <%= f.submit "Create Category", class: "first-btn" %>
  </div>
      
<% end %>
<%= link_to '/', :remote => true do %>
  <input type="button" class="first-btn" value="Back">
<% end %>

</div>
</section>
  </body>
</html>

app/views/groups/show.html.erb
<%= render "partials/nav" %>
<div class="credit">
  <h3>Gift Credit</h3>
  <h3>$<%=@group.self_total(@group.id)%>.00</h3>
</div>

<section class="main">

<%@relations.each do |relation|%>
  <%entity = Entity.find(relation.entity_id)%>
  <div class="category">
    <img src=<%=@group.icon%> alt="icon">
    
    <div class="flex">
      <h3><%=entity.name%></h3>
      <p><%=entity.created_at%></p>
    </div>
    <div class="flex">
      <h3>$<%=entity.amount%>.00</h3>
      <%= button_to "Delete", entity_path(entity.id), html: {'data-turbo' => "false"}, :method => :delete, class: "btn btn-danger" %>
    </div>
  </div>
<%end%>

<div class="flex1">

<%= link_to new_entity_path, :remote => true do %>
  <input type="button" class="btn btn-primary" value="Add transaction">
<% end %>
<%= link_to groups_path, :remote => true do %>
  <input type="button" class="btn btn-primary" value="Back">
<% end %>

</div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg">
      
      <%= link_to groups_path, :remote => true do %>
        <i class="fa fa-arrow-left fa-lg" style="color:white"></i>
      <%end%>

      <a class="navbar-brand" href="/groups">Transactions</a>
   
      <%= link_to destroy_user_session_path, method: :get do %>
        <i class="fa fa-sign-out fa-lg" style="color:white" ></i>
      <% end %>
   
   </nav>


  </body>
</html>

app/views/partials/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg">

      <i class="fa fa-arrow-left fa-lg" style="color:white"></i>

      <a class="navbar-brand" href="/groups">Categories</a>
   
      <%= link_to destroy_user_session_path, method: :get do %>
        <i class="fa fa-sign-out fa-lg" style="color:white" ></i>
      <% end %>
   
   </nav>


  </body>
</html>

app/views/splash/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <section class="body">

      <div class="box">

        <h1>Manage Budget</h1>

        <%= link_to new_user_registration_path, :class => 'navbar-link', :remote => true do  %>
          <input type="button" class="first-btn" value="SIGN UP">
        <%end%>
        <%= link_to new_user_session_path, :class => 'navbar-link', :remote => true do  %>
          <input type="button" class="first-btn" value="LOG IN">
        <%end%>
        
      </div>

    </section>
    
  </body>
</html>